# День Pandas, но ни слова про животных.

Библиотека pandas будет основным предметом изучения сегодня.
Она содержит высокоуровневые структуры данных и средства манипуляции ими, спроектированные так, чтобы обеспечить простоту и высокую скорость анализа данных на Python. Эта библиотека построена поверх NumPy, поэтому ей легко пользоваться в приложениях, ориентированных на NumPy.

Pandas легко справляется с требованиями, которые не могут быть полностью удовлетворены остальными доступными инструментов:
- Наличие структур данных с помеченными осями, поддерживающие автоматическое или явное выравнивание. Это помогает избежать типичных ошибок, связанных с невыровненностью данных и работой с данными, поступившими из разных источников и по-разному проиндексированных.
- Одни и те же структуры должны быть пригодны для обработки как временных рядов, так и данных иного характера.
- Арифметические операции и операции редуцирования (например, суммирование вдоль оси) должны «пробрасывать» метаданные (метки осей).
- Гибкая обработка отсутствующих данных.
- Объединение и другие реляционные операции, имеющиеся в популярных базах данных (например, на основе SQL).

За прошедшие четыре года pandas превратилась в довольно обширную
библиотеку, способную решать куда более широкий круг задач обработки данных, чем планировалось первоначально, но расширялась она, не принося в жертву простоту и удобство использования.

Начнем с того, что существует негласное соглашение о правилах импорта pandas, точно так же, как было и с Numpy.

In [ ]:
from pandas import Series, DataFrame
import pandas as pd

import numpy as np

## Введение в структуры данных pandas
Чтобы начать работу с pandas, вы должны освоить две основные структуры данных: Series и DataFrame. Они, конечно, не являются универсальным решением любой задачи, но все же образуют солидную и простую для использования основу большинства приложений.

### Объект Series
Series – одномерный похожий на массив объект, содержащий массив данных (любого типа, поддерживаемого NumPy) и ассоциированный с ним массив меток, который называется индексом. Простейший объект Series состоит только из массива данных:

In [ ]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

В строковом представлении Series, отображаемом в интерактивном режиме, индекс находится слева, а значения справа. Поскольку мы не задали индекс для данных, то по умолчанию создается индекс, состоящий из целых чисел от 0 до N – 1
(где N – длина массива данных). Имея объект Series, получить представление самого массива и его индекса можно с помощью атрибутов values и index соответственно:

In [ ]:
obj = Series([4, 7, -5, 3])

print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)

Часто желательно создать объект Series с индексом, идентифицирующим каждый элемент данных:

In [ ]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

print(obj2, '\n')
print(obj2.values)
print(obj2.index)

d    4
b    7
a   -5
c    3
dtype: int64

[ 4  7 -5  3]
Index(['d', 'b', 'a', 'c'], dtype='object')

В отличие от обычного массива NumPy, для выборки одного или нескольких элементов из объекта Series можно использовать значения индекса:

In [ ]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

print(obj2['d'])
obj2['d'] = 6
print(obj2[['c', 'a', 'd']])

4
c    3
a   -5
d    6
dtype: int64

Операции с массивом NumPy, например фильтрация с помощью булева массива, скалярное умножение или применение математических функций, сохраняют
связь между индексом и значением:

In [ ]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

print(obj2, '\n')
print(obj2[obj2 > 0], '\n')
print(obj2 * 2, '\n')
print(np.exp(obj2))

d    4
b    7
a   -5
c    3
dtype: int64

d    4
b    7
c    3
dtype: int64

d     8
b    14
a   -10
c     6
dtype: int64

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Объект Series можно также представлять себе как упорядоченный словарь фиксированной длины, поскольку он отображает индекс на данные. Его можно передавать многим функциям, ожидающим получить словарь.

In [ ]:
print('b' in obj2)
print('e' in obj2)

True
False

Если имеется словарь Python, содержащий данные, то из него можно создать объект Series, a в получившемся объекте Series ключи будут храниться в индексе по порядку:

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

В данном случае 3 значения, найденные в sdata, помещены в соответствующие им позиции, а для метки 'California' никакого значения не нашлось, поэтому ей соответствует признак NaN (не число), которым в pandas обозначаются отсутствующие значения. 

Иногда, говоря об отсутствующих данных, употребляется термин «NA». Для распознавания отсутствующих данных в pandas следует использовать функции isnull и notnull или метод isnull():

In [ ]:
print(pd.isnull(obj4), '\n')
print(pd.notnull(obj4), '\n')
print(obj4.isnull())

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Для многих приложений особенно важно, что при выполнении арифметических операций объект Series автоматически выравнивает данные, которые проиндексированы в разном порядке:

In [ ]:
print(obj3, '\n')
print(obj4, '\n')

sum_of_series = obj3 + obj4
print(sum_of_series, '\n')

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Вопрос о выравнивании данных будет рассмотрен отдельно.
И у самого объекта Series, и у его индекса имеется атрибут name, тесно связанный с другими частями функциональности pandas:

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Индекс объекта Series можно изменить на месте с помощью присваивания:

In [ ]:
obj = Series([4, 7, -5, 3])
print(obj, '\n')

obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### Объект DataFrame

Объект DataFrame представляет табличную структуру данных, состоящую из упорядоченной коллекции столбцов, причем типы значений (числовой, строковый, булев и т. д.) в разных столбцах могут различаться. В объекте DataFrame хранятся два индекса: по строкам и по столбцам.Можно считать, что это словарь объектов Series. 

По сравнению с другими похожими на DataFrame структурами из других языков (например, data.frame в языке R), операции со строками и столбцами в DataFrame в первом приближении симметричны.

Внутри объекта данные хранятся в виде одного или нескольких двумерных блоков, а не в виде списка, словаря или еще какой-нибудь коллекции одномерных
массивов. Технические детали внутреннего устройства DataFrame выходят за рамки этой книги.

> Хотя в DataFrame данные хранятся в двумерном формате, в виде таблицы,
нетрудно представить и данные более высокой размерности, если воспользоваться иерархическим индексированием.

Есть много способов сконструировать объект DataFrame, один из самых распространенных – на основе словаря списков одинаковой длины или массивов
NumPy:

In [1]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

frame = DataFrame(data)
frame

NameError: ignored

Если задать последовательность столбцов, то столбцы DataFrame расположатся строго в указанном порядке:

In [ ]:
DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

Как и в случае Series, если запросить столбец, которого нет в data, то он будет
заполнен значениями NaN

In [ ]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])

print(frame2.columns)
frame2

Index(['year', 'state', 'pop', 'debt'], dtype='object')

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

Столбец DataFrame можно извлечь как объект Series, воспользовавшись нотацией словарей, или с помощью атрибута:

In [ ]:
print(frame2['state'], '\n')
print(frame2.year)

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

Отметим, что возвращенный объект Series имеет тот же индекс, что и DataFrame,
а его атрибут name установлен соответствующим образом.
Строки также можно извлечь по позиции или по имени, для чего есть два метода, один из них – loc с указанием индексного поля (подробнее об этом ниже):

In [ ]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

Столбцы можно модифицировать путем присваивания. Например, пустому
столбцу 'debt' можно было бы присвоить скалярное значение или массив значений:

In [ ]:
frame2['debt'] = 16.5
frame2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [ ]:
frame2['debt'] = np.arange(5.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

Когда столбцу присваивается список или массив, длина значения должна совпадать с длиной DataFrame. Если же присваивается объект Series, то он будет точно согласован с индексом DataFrame, а в «дырки» будут вставлены значения NA:

In [ ]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val

frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

Присваивание несуществующему столбцу приводит к созданию нового столбца. Для удаления столбцов служит ключевое слово del, как и в обычном словаре:

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)

del frame2['eastern']
frame2.columns

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

Index(['year', 'state', 'pop', 'debt'], dtype='object')

>  Столбец, возвращенный в ответ на запрос к DataFrame по индексу, является представлением, а не копией данных. Следовательно, любые модификации этого объекта Series, найдут отражение в DataFrame. Чтобы скопировать столбец, нужно вызвать метод copy объекта Series

Еще одна распространенная форма данных – ***словарь словарей***. Если передать его конструктору DataFrame, то ключи внешнего словаря будут интерпретированы как столбцы, а ключи внутреннего словаря – как индексы
строк:

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

Разумеется, результат можно транспонировать:

In [ ]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

Ключи внутренних словарей объединяются и сортируются для образования индекса результата. Однако этого не происходит, если индекс задан явно:

In [ ]:
DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

Словари объектов Series интерпретируются очень похоже:

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

Полный перечень возможных аргументов конструктора DataFrame приведен ниже:

|Тип               |Примечания                                                |
|:------------------|----------------------------------------------------------:|
|Двумерный ndarray |Матрица данных, дополнительно можно передать метки строк и столбцов|
|Словарь массивов, списков или кортежей|Каждая последовательность становится столбцом объекта DataFrame. Все последовательности должны быть одинаковой длины |
|Структурный массив NumPy | Интерпретируется так же, как «словарь массивов» |
|Словарь объектов Series | Каждое значение становится столбцом. Если индекс явно не задан, то индексы объектов Series объединяются и образуют индекс строк результата|
|Словарь словарей | Каждый внутренний словарь становится столбцом. Ключи объединяются и образуют индекс строк, как в случае «словаря объектов Series»|
|Список словарей или объектов Series| Каждый элемент списка становится строкой объекта|
|DataFrame. |Объединение ключей словаря или индексов объектов Series становится множеством меток столбцов DataFrame|
|Список списков или кортежей| Интерпретируется так же, как «двумерный ndarray»|
|Другой объект DataFrame| Используются индексы DataFrame, если явно не заданы другие индексы |


Если у объектов, возвращаемых при обращении к атрибутам index и columns
объекта DataFrame, установлен атрибут name, то он также выводится:

In [ ]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

Как и в случае Series, атрибут values возвращает данные, хранящиеся в
DataFrame, в виде двумерного массива ndarray:

In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

Если у столбцов DataFrame разные типы данных, то dtype массива values будет
выбран так, чтобы охватить все столбцы:

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Индексные объекты

> Многим пользователям подробная информация об индексных объектах
не нужна, но они, тем не менее, являются важной частью модели данных
pandas.

В индексных объектах pandas хранятся метки вдоль осей и прочие метаданные (например, имена осей). Любой массив или иная последовательность меток, указанная при конструировании Series или DataFrame, преобразуется в объект Index:

In [ ]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')

#### Индексные объекты неизменяемы, т. е. пользователь не может их модифицировать!

Неизменяемость важна для того, чтобы несколько структур данных могли совместно использовать один и тот же индексный объект, не опасаясь его повредить:

In [ ]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

В таблице ниже перечислены включенные в библиотеку индексные классы. При некотором усилии можно даже создать подклассы класса Index, если требуется реализовать специализированную функциональность индексирования вдоль оси.

|Тип |Примечания|
|----|----------|
|Index |Наиболее общий индексный объект, представляющий оси в массиве NumPy, состоящем из объектов Python|
|Int64Index| Специализированный индекс для целых значений|
|MultiIndex| «Иерархический» индекс, представляющий несколько уровней индексирования по одной оси. Можно считать аналогом массива кортежей|
|DatetimeIndex| Хранит временные метки с наносекундной точностью (представлены типом данных NumPy datetime64)|
|PeriodIndex| Специализированный индекс для данных о периодах (временных промежутках)|

Индексный объект не только похож на массив, но и ведет себя как множество
фиксированного размера:

In [ ]:
print(frame3, '\n')

print('Ohio' in frame3.columns)
print(2003 in frame3.index)

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

True
False

У любого объекта Index есть ряд свойств и методов для ответа на типичные вопросы о хранящихся в нем данных. Они перечислены в таблице ниже.

|Метод |Описание|
|------|--------|
|append| Конкатенирует с дополнительными индексными объектами, порождая новый объект Index|
|diff| Вычисляет теоретико-множественную разность, представляя ее в виде индексного объекта|
|intersection| Вычисляет теоретико-множественное пересечение|
|union| Вычисляет теоретико-множественное объединение|
|isin| Вычисляет булев массив, показывающий, содержится ли каждое значение индекса в переданной коллекции|
|delete| Вычисляет новый индексный объект, получающийся после удаления элемента с индексом i|
|drop| Вычисляет новый индексный объект, получающийся после удаления переданных значений|
|insert| Вычисляет новый индексный объект, получающийся после вставки элемента в позицию с индексом i|
|is_monotonic| Возвращает True, если каждый элемент больше или равен предыдущему|
|is_unique| Возвращает True, если в индексе нет повторяющихся значений|
|unique| Вычисляет массив уникальных значений в индексе|

## Базовая функциональность

Рассмотрим фундаментальные основы взаимодействия с данными, хранящимися в объектах Series и DataFrame. Далее мы еще детально обсудим вопросы анализа и манипуляции данными с применением pandas, а сейчас лишь акцентируем внимание на наиболее важных чертах, оставив не столь употребительные вещи для дальнейшего самостоятельного изучения.

### Переиндексация

Для объектов pandas критически важен метод reindex, т. е. возможность создания нового объекта, данные в котором согласуются с новым индексом. Рассмотрим простой пример:

In [ ]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Если вызвать reindex для этого объекта Series, то данные будут реорганизованы в соответствии с новым индексом, а если каких-то из имеющихся в этом индексе значений раньше не было, то вместо них будут подставлены отсутствующие значения:

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)

print(obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0))

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

Для упорядоченных данных, например временных рядов, иногда желательно
произвести интерполяцию, или восполнение отсутствующих значений в процессе переиндексации. Это позволяет сделать параметр method; так, если задать для
него значение ffill, то будет произведено прямое восполнение значений:

In [ ]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

Ниже перечислены возможные значения параметра method. В настоящее
время интерполяцию, более сложную, чем прямое и обратное восполнение, нужно
производить постфактум.

|Значение | Описание|
|---------|---------|
|ffill или pad | Восполнить (или перенести) значения в прямом направлении|
|bfill или backfill | Восполнить (или перенести) значения в обратном направлении|

В случае объекта DataFrame функция reindex может изменять строки, столбцы
или то и другое. Если ей передать просто последовательность, то в результирующем объекте переиндексируются строки:

In [ ]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
print(frame, '\n')

frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

Столбцы можно переиндексировать, задав ключевое слово columns:

In [ ]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Строки и столбцы можно переиндексировать за одну операцию, хотя интерполяция будет применена только к строкам (к оси 0):

In [ ]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states).ffill()

   Texas  Utah  California
a    1.0   NaN         2.0
b    1.0   NaN         2.0
c    4.0   NaN         5.0
d    7.0   NaN         8.0

##### Аргументы функции reindex

|Аргумент | Описание|
|---------|---------|
|index | Последовательность, которая должна стать новым индексом. Может быть экземпляром Index или любой другой структурой данных Python, похожей на последовательность. Экземпляр Index будет использован «как есть», без копирования|
|fill_value | Значение, которой должно подставляться вместо отсутствующих значений, появляющихся в результате переиндексации|
|limit | При прямом или обратном восполнении максимальная длина восполняемой лакуны|
|level | Сопоставить с простым объектом Index на указанном уровне MultiIndex, иначе выбрать подмножество|
|copy | Не копировать данные, если новый индекс эквивалентен старому. По умолчанию True (т. е. всегда копировать данные)|

### Удаление элементов из оси
Удалить один или несколько элементов из оси просто, если имеется индексный
массив или список, не содержащий этих значений. Метод drop возвращает новый
объект, в котором указанные значения удалены из оси:

In [ ]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')

print(new_obj, '\n')
print(obj.drop(['d', 'c']))

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

В случае DataFrame указанные в индексе значения можно удалить из любой
оси:

In [ ]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

print(data.drop(['Colorado', 'Ohio']), '\n')
print(data.drop('two', axis=1), '\n')
print(data.drop(['two', 'four'], axis=1))

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Доступ по индексу, выборка и фильтрация

Доступ по индексу к объекту Series (obj[...]) работает так же, как для массивов NumPy с тем отличием, что индексами могут быть не только целые, но любые
значения из индекса объекта Series. Вот несколько примеров:

In [ ]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

print(obj['b'], '\n')
print(obj[1], '\n')
print(obj[2:4], '\n')
print(obj[['b', 'a', 'd']], '\n')
print(obj[[1, 3]], '\n')
print(obj[obj < 2])

1.0

1.0

c    2.0
d    3.0
dtype: float64

b    1.0
a    0.0
d    3.0
dtype: float64

b    1.0
d    3.0
dtype: float64

a    0.0
b    1.0
dtype: float64

Вырезание с помощью меток отличается от обычного вырезания в Python тем,
что конечная точка включается в интервал:

In [ ]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

Установка значений с помощью этих методов работает ожидаемым образом:

In [ ]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

Как мы уже видели, доступ по индексу к DataFrame применяется для извлечения одного или нескольких столбцов путем задания единственного значения или
последовательности:

In [ ]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

print(data, '\n')
print(data['two'], '\n')
print(data[['three', 'one']])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

У доступа по индексу есть несколько частных случаев. Во-первых, выборка
строк с помощью вырезания или булева массива:

In [ ]:
print(data[:2], '\n')
print(data[data['three'] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Некоторым читателям такой синтаксис может показаться непоследовательным, но он был выбран исключительно из практических соображений. Еще одна
возможность – доступ по индексу с помощью булева DataFrame, например порожденного в результате скалярного сравнения:

In [ ]:
print(data < 5, '\n')
data[data < 5] = 0
print(data)

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Идея в том, чтобы сделать DataFrame синтаксически более похожим на ndarray
в данном частном случае. Для доступа к строкам по индексу с помощью меток используются специальные методы loc и iloc. Оно позволяет выбрать подмножество строк и столбцов DataFrame с применение нотации NumPy, дополненной метками осей.

In [ ]:
print(data)

print(data.loc['Colorado', ['two', 'three']], '\n')
print(data.iloc[[3, 0, 1]], '\n')
print(data.iloc[2], '\n')
print(data.loc[:'Utah', 'two'])

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
two      5
three    6
Name: Colorado, dtype: int32

          one  two  three  four
New York   12   13     14    15
Ohio        0    0      0     0
Colorado    0    5      6     7

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

## Арифметические операции и выравнивание данных

Одна из самых важных черт pandas – поведение арифметических операций для
объектов с разными индексами. Если при сложении двух объектов обнаруживаются различные пары индексов, то результирующий индекс будет объединением
индексов. Рассмотрим простой пример: сложение этих объектов дает весьма интересный результат.

In [ ]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

print(s1, s2, sep='\n\n', end='\n\n')
print(s1 + s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

Вследствие внутреннего выравнивания данных образуются отсутствующие
значения в позициях, для которых не нашлось соответственной пары. Отсутствующие значения распространяются на последующие операции.
В случае DataFrame выравнивание производится как для строк, так и для столбцов. При сложении этих объектов получается DataFrame, индекс и столбцы которого являются объединениями индексов и столбцов слагаемых:

In [ ]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])

print(df1, df2, sep='\n\n', end='\n\n')
print(df1 + df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Восполнение значений в арифметических методах

При выполнении арифметических операций с объектами, проиндексированными по-разному, иногда желательно поместить специальное значение, например 0, в позиции операнда, которым в другом операнде соответствует отсутствующая позиция. Сложение этих объектов порождает отсутствующие значения в позициях, которые имеются не в обоих операндах.

In [ ]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

print(df1, df2, sep='\n\n', end='\n\n')
print(df1 + df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

Но если вызвать метод add объекта df1 и передать ему объект df2 и значение
параметра fill_value, то мы избавимся от `NaN`

In [ ]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Есть и другие операторы.

|Метод | Описание|
|------|---------|
|add | Сложение (+)|
|sub | Вычитание (-)|
|div | Деление (/)|
|mul | Умножение (\*)|

Точно так же, выполняя переиндексацию объекта Series или DataFrame, можно
указать восполняемое значение:

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Операции между DataFrame и Series
Как и в случае массивов NumPy, арифметические операции между DataFrame
и Series корректно определены. В качестве пояснительного примера рассмотрим
вычисление разности между двумерным массивом и одной из его строк:

In [ ]:
arr = np.arange(12.).reshape((3, 4))

print(arr, end='\n\n')
print(arr[0], end='\n\n')
print(arr - arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[0. 1. 2. 3.]

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]

Это называется *укладыванием*. Операции между DataFrame и Series аналогичны. По умолчанию при выполнении арифметических операций между DataFrame и Series индекс Series сопоставляется со столбцами DataFrame, а укладываются строки:

In [ ]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

print(frame, end='\n\n')
print(series, end='\n\n')
print(frame - series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

Если какой-нибудь индекс не найден либо в столбцах DataFrame, либо в индексе Series, то объекты переиндексируются для образования объединения:

In [ ]:
series2 = Series(range(3), index=['b', 'e', 'f'])
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Если вы хотите вместо этого сопоставлять строки, а укладывать столбцы, то
должны будете воспользоваться каким-нибудь арифметическим методом. Например:

In [ ]:
series3 = frame['d']
print(frame, end='\n\n')
print(frame.sub(series3, axis=0))

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

Передаваемый номер оси – это ось, вдоль которой производится сопоставление.
В данном случае мы хотим сопоставлять с индексом строк DataFrame и укладывать поперек.

### Применение функций и отображение
Универсальные функции NumPy (поэлементные методы массивов) отлично работают и с объектами pandas:

In [ ]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

print(frame, end='\n\n')
print(np.abs(frame))

               b         d         e
Utah   -0.173380  2.095245 -0.360159
Ohio   -1.946250 -1.306720 -0.081092
Texas  -0.131535 -1.639874  1.576470
Oregon -1.672523 -0.516514  0.402503

               b         d         e
Utah    0.173380  2.095245  0.360159
Ohio    1.946250  1.306720  0.081092
Texas   0.131535  1.639874  1.576470
Oregon  1.672523  0.516514  0.402503

Еще одна часто встречающаяся операция – применение функции, определенной для одномерных массивов, к каждому столбцу или строке. Именно это и делает метод apply объекта DataFrame:

In [ ]:
print(frame.apply(lambda x: x.max() - x.min()), end='\n\n')

print(frame.apply(lambda x: x.max() - x.min(), axis=1))

b    1.814715
d    3.735119
e    1.936629
dtype: float64

Utah      2.455404
Ohio      1.865157
Texas     3.216344
Oregon    2.075026
dtype: float64

Многие из наиболее распространенных статистик массивов (например, sum и
mean) – методы DataFrame, поэтому применять apply в этом случае необязательно. Функция, передаваемая методу apply, не обязана возвращать скалярное значение, она может вернуть и объект Series, содержащий несколько значений:

In [ ]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

            b         d         e
min -1.946250 -1.639874 -0.360159
max -0.131535  2.095245  1.576470

Можно использовать и поэлементные функции Python. Допустим, требуется
вычислить форматированную строку для каждого элемента frame с плавающей
точкой. Это позволяет сделать метод applymap. Этот метод называется applymap, потому что в классе Series есть метод map для применения функции к каждому элементу:

In [ ]:
format = lambda x: '%.2f' % x

print(frame.applymap(format), end='\n\n')
print(frame['e'].map(format))

            b      d      e
Utah    -0.17   2.10  -0.36
Ohio    -1.95  -1.31  -0.08
Texas   -0.13  -1.64   1.58
Oregon  -1.67  -0.52   0.40

Utah      -0.36
Ohio      -0.08
Texas      1.58
Oregon     0.40
Name: e, dtype: object

### Сортировка и ранжирование

Сортировка набора данных по некоторому критерию – еще одна важная встроенная операция. Для лексикографической сортировки по индексу служит метод
sort_index, который возвращает новый отсортированный объект:

In [ ]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

В случае DataFrame можно сортировать по индексу, ассоциированному с любой
осью:

In [ ]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
print(frame.sort_index())
print(frame.sort_index(axis=1))

       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4

По умолчанию данные сортируются в порядке возрастания, но можно отсортировать их и в порядке убывания:

In [ ]:
frame.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

Для сортировки Series по значениям служит метод sort_values():

In [ ]:
obj = Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

Отсутствующие значения по умолчанию оказываются в конце Series:

In [ ]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

Объект DataFrame можно сортировать по значениям в одном или нескольких
столбцах. Для этого имена столбцов следует передать в качестве значения параметра by:

In [ ]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

print(frame, '\n\n')
print(frame.sort_values(by='b'), '\n\n')

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1


   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

Для сортировки по нескольким столбцам следует передать список имен:

In [ ]:
frame.sort_values(['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

Ранжирование тесно связано с сортировкой, заключается оно в присваивании
рангов – от единицы до числа присутствующих в массиве элементов. Это аналогично косвенным индексам, порождаемым методом numpy.argsort, с тем отличием, что существует правило обработки связанных рангов. Для ранжирования
применяется метод rank объектов Series и DataFrame; по умолчанию rank обрабатывает связанные ранги, присваивая каждой группе средний ранг:

In [ ]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ранги можно также присваивать в соответствии с порядком появления в данных:

In [ ]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

Естественно, можно ранжировать и в порядке убывания:

In [ ]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

Все допустимые способы обработки связанных рангов приведены в таблице ниже:
    
|Способ| Описание|
|---|---|
|'average'| По умолчанию: одинаковым значениям присвоить средний ранг|
|'min'| Всем элементам группы присвоить минимальный ранг|
|'max'| Всем элементам группы присвоить максимальный ранг|
|'first'| Присваивать ранги в порядке появления значений в наборе данных|

DataFrame умеет вычислять ранги как по строкам, так и по столбцам:

In [ ]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})

print(frame, '\n\n')
print(frame.rank(axis=1))

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5


     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Индексы по осям с повторяющимися значениями

Во всех рассмотренных до сих пор примерах метки на осях (значения индекса)
были уникальны. Хотя для многих функций pandas (например, reindex) требуется уникальность меток, в общем случае это необязательно. Рассмотрим небольшой объект Series с повторяющимися значениями в индексе:

In [ ]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

О том, являются значения уникальными или нет, можно узнать, опросив свойство is_unique:

In [ ]:
obj.index.is_unique

False

Выборка данных – одна из основных операций, поведение которых меняется
в зависимости от наличия или отсутствия дубликатов. При доступе по индексу,
встречающемуся несколько раз, возвращается объект Series; если же индекс одиночный, то скалярное значение. Такое же правило действует и для доступа к строкам в DataFrame:

In [ ]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
print(obj['a'])
print(obj['c'])

df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
print(df)
print(df.loc['b'])

a    0
a    1
dtype: int64
4
          0         1         2
a  1.141556  0.108649  1.507457
a  0.607618 -0.988929  1.200559
b  0.305507 -2.656558 -0.863610
b -0.552541 -1.038692 -0.648819
          0         1         2
b  0.305507 -2.656558 -0.863610
b -0.552541 -1.038692 -0.648819

### Редукция и вычисление описательных статистик

Объекты pandas оснащены набором стандартных математических и статистических методов. Большая их часть попадает в категорию редукций, или сводных статистик – методов, которые вычисляют единственное значение (например, сумму
или среднее) для Series или объект Series – для строк либо столбцов DataFrame.
По сравнению с эквивалентными методами массивов NumPy, все они игнорируют
отсутствующие значения. Рассмотрим небольшой объект DataFrame:

In [ ]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Метод sum объекта DataFrame возвращает Series, содержащий суммы по столбцам. Если передать параметр axis=1, то суммирование будет производиться по строкам

In [ ]:
print(df.sum())
print(df.sum(axis=1))

one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

Отсутствующие значения исключаются, если только не является отсутствующим весь срез (в данном случае строка или столбец). Это можно подавить, задав параметр skipna:

In [ ]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

Некоторые методы, например idxmin и idxmax, возвращают косвенные статистики, скажем, индекс, при котором достигается минимум или максимум:

In [ ]:
 df.idxmax()

one    b
two    d
dtype: object

Есть также аккумулирующие методы:

In [ ]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

Наконец, существуют методы, не относящиеся ни к редуцирующим, ни к аккумулирующим. Примером может служить метод describe, который возвращает несколько сводных статистик за одно обращение. В случае нечисловых данных describe возвращает другие сводные статистики.

In [ ]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
print(df.describe(), '\n\n')

obj = Series(['a', 'a', 'b', 'c'] * 4)
print(obj.describe())

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000


count     16
unique     3
top        a
freq       8
dtype: object

Это лишь пример некоторых описательных статистик. Перечень всех описательных статистик представлен ниже:

|Метод| Описание|
|----|----|
|count| Количество значений, исключая отсутствующие|
|describe| Вычисляет набор сводных статистик для Series или для каждого столбца DataFrame|
|min, max| Вычисляет минимальное или максимальное значение
|argmin, argmax| Вычисляет позицию в индексе (целые числа), при котором достигается минимальное или максимальное значение соответственно|
|idxmin, idxmax| Вычисляет значение индекса, при котором достигается минимальное или максимальное значение соответственно|
|quantile| Вычисляет выборочный квантиль в диапазоне от 0 до 1|
|sum| Сумма значений|
|mean| Среднее значение|
|median| Медиана (50%-ый квантиль)|
|mad| Среднее абсолютное отклонение от среднего|
|var| Выборочная дисперсия|
|std| Выборочное стандартное отклонение|
|skew| Асимметрия (третий момент)|
|kurt| Куртозис (четвертый момент)|
|cumsum| Нарастающая сумма|
|cummin, cummax| Нарастающий минимум или максимум соответственно|
|cumprod| Нарастающее произведение|
|diff| Первая арифметическая разность (полезно для временных рядов)|
|pct_change| Вычисляет процентное изменение|


## Корреляция и ковариация

Некоторые сводные статистики, например корреляция и ковариация, вычисляются по парам аргументов. Рассмотрим объекты DataFrame, содержащие цены акций и объемы биржевых сделок, взятые с сайта Yahoo! Finance. Вычислим процентные изменения цен для каждого типа акций.

> P.S. для получения данных воспользуемся модулем pandas-datareader. Устанавливается командами `pip install pandas-datareader` или `conda install pandas-datareader`

In [ ]:
from pandas_datareader import data as web
all_data = {}

for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')
all_data

C:\Anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

{'AAPL':                 High       Low      Open     Close       Volume  Adj Close
 Date
 1999-12-31  0.918527  0.888393  0.901228  0.917969  163811200.0   0.793253
 2000-01-03  1.004464  0.907924  0.936384  0.999442  535796800.0   0.863657
 2000-01-04  0.987723  0.903460  0.966518  0.915179  512377600.0   0.790842
 2000-01-05  0.987165  0.919643  0.926339  0.928571  778321600.0   0.802415
 2000-01-06  0.955357  0.848214  0.947545  0.848214  767972800.0   0.732975
 ...              ...       ...       ...       ...          ...        ...
 2009-12-24  7.476786  7.262500  7.269643  7.465714  500889200.0   6.451417
 2009-12-28  7.641071  7.486072  7.561429  7.557500  644565600.0   6.530730
 2009-12-29  7.597143  7.454643  7.593928  7.467857  445205600.0   6.453269
 2009-12-30  7.571429  7.439643  7.458214  7.558571  412084400.0   6.531657
 2009-12-31  7.619643  7.520000  7.611786  7.526072  352410800.0   6.503574

 [2516 rows x 6 columns],
 'IBM':                   High         Low        Open       Close      Volume  \
 Date
 1999-12-31  109.500000  106.625000  109.187500  107.875000   2870300.0
 2000-01-03  116.000000  111.875000  112.437500  116.000000  10347700.0
 2000-01-04  114.500000  110.875000  114.000000  112.062500   8227800.0
 2000-01-05  119.750000  112.125000  112.937500  116.000000  12733200.0
 2000-01-06  118.937500  113.500000  118.000000  114.000000   7971900.0
 ...                ...         ...         ...         ...         ...
 2009-12-24  130.570007  129.479996  129.889999  130.570007   4265100.0
 2009-12-28  132.309998  130.720001  130.990005  132.309998   5800400.0
 2009-12-29  132.369995  131.800003  132.279999  131.850006   4184200.0
 2009-12-30  132.679993  130.679993  131.229996  132.570007   3867000.0
 2009-12-31  132.850006  130.750000  132.410004  130.899994   4223400.0

             Adj Close
 Date
 1999-12-31  68.497292
 2000-01-03  73.656433
 2000-01-04  71.156227
 2000-01-05  73.656433
 2000-01-06  72.386459
 ...               ...
 2009-12-24  92.173180
 2009-12-28  93.401497
 2009-12-29  93.076752
 2009-12-30  93.585014
 2009-12-31  92.406113

 [2516 rows x 6 columns],
 'MSFT':                  High        Low       Open      Close      Volume  Adj Close
 Date
 1999-12-31  58.875000  58.125000  58.750000  58.375000  12517600.0  37.259617
 2000-01-03  59.312500  56.000000  58.687500  58.281250  53228400.0  37.199776
 2000-01-04  58.562500  56.125000  56.781250  56.312500  54119000.0  35.943153
 2000-01-05  58.187500  54.687500  55.562500  56.906250  64059600.0  36.322121
 2000-01-06  56.937500  54.187500  56.093750  55.000000  54976600.0  35.105415
 ...               ...        ...        ...        ...         ...        ...
 2009-12-24  31.000000  30.760000  30.879999  31.000000  11083900.0  24.207516
 2009-12-28  31.180000  30.889999  31.000000  31.170000  25384000.0  24.340267
 2009-12-29  31.500000  31.230000  31.350000  31.389999  29716200.0  24.512062
 2009-12-30  31.290001  30.799999  31.150000  30.959999  42006200.0  24.176279
 2009-12-31  30.990000  30.480000  30.980000  30.480000  31929700.0  23.801456

 [2516 rows x 6 columns],
 'GOOG':                   High         Low        Open       Close    Volume  \
 Date
 2004-08-19   51.835709   47.800831   49.813286   49.982655  44871300
 2004-08-20   54.336334   50.062355   50.316402   53.952770  22942800
 2004-08-23   56.528118   54.321388   55.168217   54.495735  18342800
 2004-08-24   55.591629   51.591621   55.412300   52.239193  15319700
 2004-08-25   53.798351   51.746044   52.284027   52.802086   9232100
 ...                ...         ...         ...         ...       ...
 2009-12-24  308.603271  304.991821  305.320587  308.085236   1723800
 2009-12-28  311.826202  308.085236  309.669281  310.272034   3408400
 2009-12-29  311.253357  307.990570  311.203522  308.543518   2860200
 2009-12-30  310.202271  307.851105  308.095184  310.202271   2942100
 2009-12-31  311.532288  308.832428  311.208527  308.832428   2448700

              Adj Close
 Date
 2004-08-19   49.982655
 2004-08-20   53.952770
 2004-08-23   54.495735
 2004-08-24   52.239193
 2004-08-25   52.802086
 ...                ...
 2009-12-24  308.085236
 2009-12-28  310.272034
 2009-12-29  308.543518
 2009-12-30  310.202271
 2009-12-31  308.832428

 [1353 rows x 6 columns]}

In [ ]:
price = DataFrame({tic: data['Adj Close'] for tic, data in all_data.items()})
volume = DataFrame({tic: data['Volume'] for tic, data in all_data.items()})

returns = price.pct_change()
returns.tail()

                AAPL       IBM      MSFT      GOOG
Date
2009-12-24  0.034339  0.004385  0.002587  0.011117
2009-12-28  0.012294  0.013326  0.005484  0.007098
2009-12-29 -0.011861 -0.003477  0.007058 -0.005571
2009-12-30  0.012147  0.005461 -0.013699  0.005376
2009-12-31 -0.004299 -0.012597 -0.015504 -0.004416

Метод corr объекта Series вычисляет корреляцию перекрывающихся, отличных от NA, выровненных по индексу значений в двух объектах Series. Соответственно, метод cov вычисляет ковариацию.

С другой стороны, методы corr и cov объекта DataFrame возвращают соответственно полную корреляционную или ковариационную матрицу в виде DataFrame.

In [ ]:
print(returns.MSFT.corr(returns.IBM))
print(returns.MSFT.cov(returns.IBM), '\n\n')

print(returns.corr(), '\n')
print(returns.cov())

0.4943579912733758
0.000215821315591899


          AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.412392  0.423598  0.470676
IBM   0.412392  1.000000  0.494358  0.390688
MSFT  0.423598  0.494358  1.000000  0.443586
GOOG  0.470676  0.390688  0.443586  1.000000

          AAPL       IBM      MSFT      GOOG
AAPL  0.001030  0.000254  0.000309  0.000303
IBM   0.000254  0.000369  0.000216  0.000142
MSFT  0.000309  0.000216  0.000516  0.000205
GOOG  0.000303  0.000142  0.000205  0.000580

С помощью метода corrwith объекта DataFrame можно вычислить попарные
корреляции между столбцами или строками DataFrame и другим объектом Series
или DataFrame. Если передать ему объект Series, то будет возвращен Series, содержащий значения корреляции, вычисленные для каждого столбца:

In [ ]:
returns.corrwith(returns.IBM)

AAPL    0.412392
IBM     1.000000
MSFT    0.494358
GOOG    0.390688
dtype: float64

Если передать объект DataFrame, то будут вычислены корреляции столбцов с
соответственными именами. Если передать axis=1, то будут вычислены корреляции строк. Во всех случаях
перед началом вычислений данные выравниваются по меткам.

Вычислим корреляции процентных изменений с объемом сделок:

In [ ]:
returns.corrwith(volume)

AAPL   -0.057665
IBM    -0.006592
MSFT   -0.014228
GOOG    0.062647
dtype: float64

## Уникальные значения, счетчики значений и членство

Еще один класс методов служит для извлечения информации о значениях, хранящихся в одномерном объекте Series. Для иллюстрации рассмотрим метод unique, который возвращает массив уникальных значений в Series:

In [ ]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

Уникальные значения необязательно возвращаются в отсортированном порядке, но могут быть отсортированы впоследствии, если это необходимо (uniques. sort()). Метод value_counts вычисляет объект Series, содержащий частоты встречаемости значений:

In [ ]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

Для удобства этот объект отсортирован по значениям в порядке убывания.
Функция value_counts может быть также вызвана как метод pandas верхнего
уровня и в таком случае применима к любому массиву или последовательности:

In [ ]:
pd.value_counts(obj.values, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

Наконец, метод isin вычисляет булев вектор членства в множестве и может
быть полезен для фильтрации набора данных относительно подмножества значений в объекте Series или столбце DataFrame:

In [ ]:
mask = obj.isin(['b', 'c'])
print(mask, '\n')
print(obj[mask])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

0    c
5    b
6    b
7    c
8    c
dtype: object

|Метод| Описание|
|---|---|
|isin| Вычисляет булев массив, показывающий, содержится ли каждое принадлежащее Series значение в переданной последовательности|
|unique| Вычисляет массив уникальных значений в Series и возвращает их в порядке появления|
|value_counts| Возвращает объект Series, который содержит уникальное значение в качестве индекса и его частоту в качестве соответствующего значения. Отсортирован в порядке убывания частот|

Иногда требуется вычислить гистограмму нескольких взаимосвязанных столбцов в DataFrame. Приведем пример:

In [ ]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4],
                  'Qu2': [2, 3, 1, 2, 3],
                  'Qu3': [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

Передача pandas.value_counts методу apply этого объекта DataFrame дает:

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Обработка отсутствующих данных

Отсутствующие данные – типичное явление в большинстве аналитических приложений. При проектировании pandas в качестве одной из целей ставилась задача сделать работу с отсутствующими данными как можно менее болезненной.

Например, выше мы видели, что при вычислении всех описательных статистик для объектов pandas отсутствующие данные не учитываются. В pandas для представления отсутствующих данных в любых массивах – как чисел с плавающей точкой, так и иных – используется значение с плавающей точкой NaN (не число). Это просто признак, который легко распознать. Встроенное в Python значение None также рассматривается как отсутствующее в массивах объектов:

In [ ]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])

print(string_data, '\n')
print(string_data.isnull(), '\n')

string_data[0] = None
print(string_data.isnull())

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

0    False
1    False
2     True
3    False
dtype: bool

0     True
1    False
2     True
3    False
dtype: bool

Никто не утверждает, что представление отсутствующих значений в pandas оптимально, но оно простое и в разумной степени последовательное. Поскольку разработка NumPy и pandas продолжается, в будущем ситуация может измениться.

Для работы с отсутствующими данными используются следующие методы:


|Аргумент| Описание|
|----|----|
|dropna| Фильтрует метки оси в зависимости от того, существуют ли для метки отсутствующие данные, причем есть возможность указать различные пороги, определяющие, какое количество отсутствующих данных считать допустимым|
|fillna| Восполняет отсутствующие данные указанным значением или использует какой-нибудь метод интерполяции, например 'ffill' или 'bfill'|
|isnull| Возвращает объект, содержащий булевы значения, которые показывают, какие значения отсутствуют|
|notnull| Логическое отрицание isnull|


## Фильтрация отсутствующих данных
Существует ряд средств для фильтрации отсутствующих данных. Конечно,
можно сделать это и вручную, но часто бывает полезен метод dropna. Для Series он
возвращает другой объект Series, содержащий только данные и значения индекса,
отличные от NA:

In [ ]:
from numpy import nan as NA

data = Series([1, NA, 3.5, NA, 7])
print(data.dropna())

0    1.0
2    3.5
4    7.0
dtype: float64

Естественно, это можно было бы вычислить и самостоятельно с помощью булевой индексации:

In [ ]:
print(data[data.notnull()])

0    1.0
2    3.5
4    7.0
dtype: float64

В случае объектов DataFrame все немного сложнее. Можно отбрасывать строки или столбцы, если они содержат только NA-значения или хотя бы одно NA-значение. По умолчанию метод dropna отбрасывает все строки, содержащие хотя бы одно отсутствующее значение.

In [ ]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()

print('BEFORE', data, '\n', sep='\n')
print('AFTER', cleaned, sep='\n')

BEFORE
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


AFTER
     0    1    2
0  1.0  6.5  3.0

Если передать параметр how='all', то будут отброшены строки, которые целиком состоят из отсутствующих значений:

In [ ]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Для отбрасывания столбцов достаточно передать параметр axis=1:

In [ ]:
data[4] = NA

print('BEFORE', data, '\n', sep='\n')
print('AFTER', data.dropna(axis=1, how='all'), sep='\n')

BEFORE
     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN


AFTER
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Родственный способ фильтрации строк DataFrame в основном применяется
к временным рядам. Допустим, требуется оставить только строки, содержащие
определенное количество наблюдений. Этот порог можно задать с помощью аргумента thresh (сокр. threshold):

In [ ]:
df = DataFrame(np.random.randn(7, 3))
print(df, '\n')

df.iloc[:4, 1] = NA;
df.iloc[:2, 2] = NA

print(df, '\n')
print('Строки с 1 и более наблюдением:', df.dropna(thresh=1), '\n', sep='\n')
print('Строки с 2 и более наблюдениями:', df.dropna(thresh=2), '\n', sep='\n')
print('Строки с 3 и более наблюдениями:', df.dropna(thresh=3), sep='\n')

          0         1         2
0  1.552756  0.231707 -0.794530
1 -1.111666 -0.212516 -0.793549
2  1.501096 -0.748794 -2.029954
3 -0.597913 -1.305985  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939

          0         1         2
0  1.552756       NaN       NaN
1 -1.111666       NaN       NaN
2  1.501096       NaN -2.029954
3 -0.597913       NaN  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939

Строки с 1 и более наблюдением:
          0         1         2
0  1.552756       NaN       NaN
1 -1.111666       NaN       NaN
2  1.501096       NaN -2.029954
3 -0.597913       NaN  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939


Строки с 2 и более наблюдениями:
          0         1         2
2  1.501096       NaN -2.029954
3 -0.597913       NaN  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939


Строки с 3 и более наблюдениями:
          0         1         2
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939

### Восполнение отсутствующих данных

Иногда отсутствующие данные желательно не отфильтровывать (и потенциально вместе с ними отбрасывать полезные данные), а каким-то способом заполнить «дыры». В большинстве случаев для этой цели можно использовать метод fillna. Ему передается константа, подставляемая вместо отсутствующих
значений:

In [ ]:
df.fillna(0)

          0         1         2
0  1.552756  0.000000  0.000000
1 -1.111666  0.000000  0.000000
2  1.501096  0.000000 -2.029954
3 -0.597913  0.000000  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939

Метод fillna возвращает новый объект, но можно также модифицировать существующий объект на месте. Если передать методу fillna словарь, то можно будет подставлять вместо отсутствующих данных значение, зависящее от столбца:

In [ ]:
print(df.fillna({1: 0.5, 3: -1}))

_ = df.fillna(0, inplace=True) # fillna всегда возвращает ссылку, поэтому всё в лучших традициях
                               # парадигмы КДВ программирования

          0         1         2
0  1.552756  0.500000       NaN
1 -1.111666  0.500000       NaN
2  1.501096  0.500000 -2.029954
3 -0.597913  0.500000  0.333352
4  0.268615  0.919014 -0.469670
5 -1.875546  0.555572  0.753698
6 -0.978025 -0.596511  0.186939

Те же методы интерполяции, что применяются для переиндексации, годятся и
для fillna:

In [ ]:
df = DataFrame(np.random.randn(6, 3))
print(df, '\n')

df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA

print(df, '\n')
print('Заполнение всех NA:', df.fillna(method='ffill'), '\n', sep='\n')
print('Заполнение NA, в строках, не более чем 1 NA:',
      df.fillna(method='ffill', limit=2), sep='\n')

          0         1         2
0 -0.848593  1.453884  0.436935
1  0.342533 -0.467886 -0.068203
2  0.527791 -0.735370 -1.011975
3 -1.542862 -0.840132 -1.207187
4 -0.138667 -0.540479  0.294936
5  0.004154  0.882729  0.284332

          0         1         2
0 -0.848593  1.453884  0.436935
1  0.342533 -0.467886 -0.068203
2  0.527791       NaN -1.011975
3 -1.542862       NaN -1.207187
4 -0.138667       NaN       NaN
5  0.004154       NaN       NaN

Заполнение всех NA:
          0         1         2
0 -0.848593  1.453884  0.436935
1  0.342533 -0.467886 -0.068203
2  0.527791 -0.467886 -1.011975
3 -1.542862 -0.467886 -1.207187
4 -0.138667 -0.467886 -1.207187
5  0.004154 -0.467886 -1.207187


Заполнение NA, в строках, не более чем 1 NA:
          0         1         2
0 -0.848593  1.453884  0.436935
1  0.342533 -0.467886 -0.068203
2  0.527791 -0.467886 -1.011975
3 -1.542862 -0.467886 -1.207187
4 -0.138667       NaN -1.207187
5  0.004154       NaN -1.207187

При некоторой изобретательности можно использовать fillna и другими способами. Например, можно передать среднее или медиану объекта Series:

In [ ]:
data = Series([1., NA, 3.5, NA, 7])

data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

Справочная информация о методе fillna приведена ниже:

|Аргумент| Описание|
|---|---|
|value| Скалярное значение или похожий на словарь объект для восполнения отсутствующих значений|
|method| Метод интерполяции. По умолчанию, если не задано других аргументов, предполагается метод 'ffill'|
|axis| Ось, по которой производится восполнение. По умолчанию axis=0|
|inplace| Модифицировать исходный объект, не создавая копию|
|limit| Для прямого и обратного восполнения максимальное количество непрерывных заполняемых промежутков|

# Чтение и запись данных, форматы файлов

## Чтение и запись данных в текстовом формате
Python превратился в излюбленный язык манипулирования текстом и файлами благодаря простому синтаксису взаимодействия с файлами, интуитивно понятным структурам данных и таким удобным средствам, как упаковка и распаковка кортежей.
В библиотеке pandas имеется ряд функций для чтения табличных данных, представленных в виде объекта DataFrame. Все они перечислены в таблице ниже, хотя чаще всего вы будете иметь дело с функциями read_csv и read_table.

|Функция| Описание|
|---|---|
|read_csv| Загружает данные с разделителями из файла, URL-адреса или похожего на файл объекта. По умолчанию разделителем является запятая|
|read_table| Загружает данные с разделителями из файла, URL-адреса или похожего на файл объекта. По умолчанию разделителем является символ табуляции ('\t')|
|read_fwf| Читает данные в формате с фиксированной шириной столбцов (без разделителей)|
|read_clipboard| Вариант read_table, который читает данные из буфера обмена. Полезно для преобразования в таблицу данных на веб-странице|


Краткий обзор этих функций, которые служат для преобразования текстовых данных в объект DataFrame. Их параметры можно отнести к нескольким
категориям:
- индексирование: какие столбцы рассматривать как индекс возвращаемого
DataFrame и откуда брать имена столбцов: из файла, от пользователя или
вообще ниоткуда;
- выведение типа и преобразование данных: включает определенные пользователем преобразования значений и список маркеров отсутствующих данных;
- разбор даты и времени: включает средства комбинирования, в том числе
сбор данных о дате и времени из нескольких исходных столбцов в один
результирующий;
- итерирование: поддержка обхода очень больших файлов;
- проблемы «грязных» данных: пропуск заголовка или концевика, комментариев и другие мелочи, например, обработка числовых данных, в которых
тройки разрядов разделены запятыми.

Выведение типа – одна из самых важных черт этих функций; это означает, что пользователю необязательно явно задавать, содержат столбцы данные с плавающей точкой, целочисленные, булевы или строковые. Правда, для обработки дат и нестандартных типов требуется больше усилий. Начнем с текстового файла, содержащего короткий список данных через запятую (формат CSV). Поскольку данные разделены запятыми, мы можем прочитать их в DataFrame с
помощью функции read_csv:

In [ ]:
df = pd.read_csv('d1_files/ex1.txt')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Можно было бы также воспользоваться функцией read_table, указав разделитель.

In [ ]:
pd.read_table('d1_files/ex1.txt', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

В файле не всегда есть строка-заголовок. Прочитать его можно двумя способами. Можно поручить pandas выбор имен
столбцов по умолчанию, а можно задать их самостоятельно:

In [ ]:
print(pd.read_csv('d1_files/ex2.txt',
                  header=None), '\n\n')
print(pd.read_csv('d1_files/ex2.txt',
                  names=['a', 'b', 'c', 'd', 'message']))

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo


   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Допустим, мы хотим, чтобы столбец message стал индексом возвращаемого объекта DataFrame. Этого можно добиться, задав аргумент index_col, в котором указать, что индексом будет столбец с номером 4 или с именем 'message':

In [ ]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('d1_files/ex2.txt',
            names=names,
            index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

Если вы хотите сформировать иерархический индекс из нескольких столбцов, то просто передайте список их номеров или имен:

In [ ]:
parsed = pd.read_csv('d1_files/ex2_multiIndex.txt',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

Иногда в таблице нет фиксированного разделителя, а для разделения полей используются пробелы или еще какой-то символ. В таком случае можно передать функции read_table регулярное выражение вместо разделителя. Рассмотрим такой текстовый файл, в котором поля разделены переменным числом пробелов и, хотя можно
было бы переформатировать данные вручную, проще передать регулярное выражение \s+:

In [ ]:
result = pd.read_table('d1_files/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Поскольку имен столбцов на одно меньше, чем число строк, read_table делает вывод, что в данном частном случае первый столбец должен быть индексом
DataFrame.

У функций разбора много дополнительных аргументов, которые помогают справиться с широким разнообразием файловых форматов. Например, параметр skiprows позволяет пропустить первую, третью и четвертую строку файла:

In [ ]:
pd.read_csv('d1_files/ex4.txt', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Обработка отсутствующих значений – важная и зачастую сопровождаемая тонкими нюансами часть разбора файла. Отсутствующие значения обычно либо вообще опущены (пустые строки), либо представлены специальными маркерами. По умолчанию в pandas используется набор общеупотребительных маркеров: `NA`, `-1.#IND` и `NULL`:

In [ ]:
result = pd.read_csv('d1_files/ex5.txt')

print(result)
print(pd.isnull(result))

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo
   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

Параметр na_values может принимать список или множество строк, рассматриваемых как маркеры отсутствующих значений:

In [ ]:
result = pd.read_csv('d1_files/ex5.txt', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Если в разных столбцах применяются разные маркеры, то их можно задать с
помощью словаря:

In [ ]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}

pd.read_csv('d1_files/ex5.txt', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

#### Аргументы функций read_csv и read_table


|Аргумент| Описание|
|:---:|:---|
|path| Строка, обозначающая путь в файловой системе, URL-адрес или похожий на файл объект|
|sep / delimiter| Последовательность символов или регулярное выражение, служащее для разделения полей в строке|
|header| Номер строки, содержащей имена столбцов. По умолчанию равен 0 (первая строка). Если строки-заголовка нет, должен быть равен None|
|index_col| Номера или имена столбцов, трактуемых как индекс строк в результирующем объекте. Может быть задан один номер (имя) или список номеров (имен), определяющий иерархический индекс
|names| Список имен столбцов результирующего объекта, задается, если header=None|
|skiprows| Количество игнорируемых начальных строк или список номеров игнорируемых строк (нумерация начинается с 0)|
|na_values| Последовательность значений, интерпретируемых как маркеры отсутствующих данных|
|comment| Один или несколько символов, начинающих комментарий, который продолжается до конца строки|
|parse_dates| Пытаться разобрать данные как дату и время; по умолчанию False. Если равен True, то производится попытка разобрать все столбцы. Можно также задать список столбцов, которые следует объединить перед разбором (если, например, время и даты заданы в разных столбцах)|
|keep_date_col| В случае, когда для разбора данных столбцы объединяются, следует ли отбрасывать объединенные столбцы. По умолчанию True|
|converters| Словарь, содержащий отображение номеров или имен столбцов на функции. Например, {'foo': f} означает, что нужно применить функцию f ко всем значением в столбце foo|
|dayfirst| При разборе потенциально неоднозначных дат предполагать международный формат (т. е. 7/6/2012 означает «7 июня 2012»). По умолчанию False|
|date_parser| Функция, применяемая для разбора дат|
|nrows| Количество читаемых строк от начала файла|
|iterator| Возвращает объект TextParser для чтения файла порциями|
|chunksize| Размер порции при итерировании|
|skip_footer| Сколько строк в конце файла игнорировать|
|verbose| Печатать разного рода информацию о ходе разбора, например, количество отсутствующих значений, помещенных в нечисловые столбцы|
|encoding| Кодировка текста в случае Unicode. Например, 'utf-8' означает, что текст представлен в кодировке UTF-8|
|squeeze| Если в результате разбора данных оказалось, что имеется только один столбец, вернуть объект Series|
|thousands| Разделитель тысяч, например, ',' или '.'|


## Чтение текстовых файлов порциями
Для обработки очень больших файлов или для того чтобы определить правильный набор аргументов, необходимых для обработки большого файла, иногда требуется прочитать небольшой фрагмент файла или последовательно читать файл
небольшими порциями .

In [ ]:
result = pd.read_csv('d1_files/ex6.txt')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

Чтобы прочитать только небольшое число строк (а не весь файл), нужно задать
это число в параметре nrows:

In [ ]:
pd.read_csv('d1_files/ex6.txt', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

Для чтения файла порциями задайте с помощью параметра chunksize размер
порции в строках:

In [ ]:
chunker = pd.read_csv('d1_files/ex6.txt', chunksize=1000)
chunker

Объект TextParser, возвращаемый функцией read_csv, позволяет читать
файл порциями размера chunksize. Например, можно таким образом итеративно
читать файл ex6.csv, агрегируя счетчики значений в столбце 'key':

In [ ]:
chunker = pd.read_csv('d1_files/ex6.txt', chunksize=1000)

tot = Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)

tot[:10]

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

У объекта TextParser имеется также метод get_chunk, который позволяет читать куски произвольного размера.


### Вывод данных в текстовом формате
Данные можно экспортировать в формате с разделителями. Рассмотрим одну
из приведенных выше операций чтения CSV-файла:

In [ ]:
data = pd.read_csv('d1_files/ex5.txt')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

С помощью метода to_csv объекта DataFrame мы можем вывести данные в
файл через запятую. Конечно, допустимы и другие разделители (при выводе в sys.stdout результат отправляется на стандартный вывод, обычно на экран):

In [ ]:
import sys

data.to_csv(sys.stdout)
print()
data.to_csv(sys.stdout, sep='|')

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

Отсутствующие значения представлены пустыми строками. Но можно вместо
этого указать какой-нибудь маркер:

In [ ]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

Если не указано противное, выводятся метки строк и столбцов. Но и те, и другие можно подавить:

In [ ]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

Можно также вывести лишь подмножество столбцов, задав их порядок:

In [ ]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

У объекта Series также имеется метод to_csv:

In [ ]:
dates = pd.date_range('1/1/2000', periods=7)
ts = Series(np.arange(7), index=dates)
ts.to_csv('d1_files/csv_out.csv')

## Ручная обработка данных в формате с разделителями

Как правило, табличные данные можно загрузить с диска с помощью функции
pandas.read_table и родственных ей. Но иногда требуется ручная обработка. Не
так уж необычно встретить файл, в котором одна или несколько строк сформированы неправильно, что сбивает read_table. Для иллюстрации базовых средств
рассмотрим небольшой CSV-файл, содержимое которого выглядит следующим образом:

> "a","b","c"<br>
"1","2","3"<br>
"1","2","3","4"<br>

Для любого файла с односимвольным разделителем можно воспользоваться
стандартным модулем Python `csv`. Для этого передайте открытый файл или объект, похожий на файл, методу `csv.reader`:

In [ ]:
import csv
f = open('d1_files/ex7.csv')
reader = csv.reader(f)

Итерирование файла с помощью объекта reader дает кортежи значений в каждой строке после удаления кавычек:

In [ ]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3', '4']

Далее можно произвести любые манипуляции, необходимые для преобразования данных к нужному виду. Например:

In [ ]:
lines = list(csv.reader(open('d1_files/ex7.csv')))
header, values = str(lines[0]).split(','), lines[1:]
data_dict = {h: v for h, v in zip(header, zip(*values))}

data_dict

{"['a'": ('1', '1'), " 'b'": ('2', '2'), " 'c']": ('3', '3')}

Встречаются различные вариации CSV-файлов. Для определения нового формата со своим разделителем, соглашением об употреблении кавычек и способе завершения строк необходимо определить простой подкласс класса csv.Dialect:

In [ ]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL
    
reader = csv.reader(f, dialect=my_dialect)

Возможные атрибуты csv.Dialect вместе с назначением каждого описаны ниже:

|Аргумент| Описание|
|---|---|
|delimiter| Односимвольная строка, определяющая разделитель полей. По умолчанию ','|
|lineterminator| Завершитель строк при выводе, по умолчанию '\r\n'. Объект reader игнорирует этот параметр, используя вместо него платформенное соглашение о концах строк|
|quotechar| Символ закавычивания для полей, содержащих специальные символы (например, разделитель). По умолчанию '"'|
|quoting| Соглашение об употреблении кавычек. Допустимые значения: csv.QUOTE_ALL (заключать в кавычки все поля), csv.QUOTE_MINIMAL (только поля, содержащие специальные символы, например разделитель), csv.QUOTE_NONNUMERIC и csv.QUOTE_NON (не заключать в кавычки). По умолчанию QUOTE_MINIMAL|
|skipinitialspace| Игнорировать пробелы после каждого разделителя. По умолчанию False|
|doublequote| Как обрабатывать символ кавычки внутри поля. Если True, добавляется второй символ кавычки. Полное описание поведения см. в документации.|
|escapechar| Строка для экранирования разделителя в случае, когда quoting равно csv.QUOTE_NONE. По умолчанию экранирование выключено|

> Если в файле употребляются более сложные или фиксированные многосимвольные разделители, то воспользоваться модулем csv не удастся. В таких случаях придется разбивать строку на части и производить другие действия по очистке данных, применяя метод строки split или метод регулярного выражения re.split.

Для записи файлов с разделителями вручную можно использовать метод csv.writer. Он принимает объект, который представляет открытый, допускающий запись файл, и те же параметры диалекта и форматирования, что csv.reader:

In [ ]:
with open('d1_files/mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))
    
pd.read_csv('d1_files/mydata.csv', sep=';')

   one  two  three
0    1    2      3
1    4    5      6
2    7    8      9

## Преобразование данных

До сих пор мы в этой главе занимались реорганизацией данных. Фильтрация, очистка и прочие преобразования составляют еще один, не менее важный, класс операций.


### Устранение дубликатов
Строки-дубликаты могут появиться в объекте DataFrame по разным причинам.
Приведем пример:

In [ ]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

Метод duplicated возвращает булев объект Series, который для каждой строки
показывает, есть в ней дубликаты или нет:

In [ ]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

А метод drop_duplicates возвращает DataFrame, для которого массив
duplicated будет содержать только значения True:

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

По умолчанию оба метода принимают во внимание все столбцы, но можно
указать произвольное подмножество столбцов, которые необходимо исследовать
на наличие дубликатов. Допустим, есть еще один столбец значений, и мы хотим
отфильтровать строки, которые содержат повторяющиеся значения в столбце
'k1':

In [ ]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
3  two   3   3

По умолчанию методы duplicated и drop_duplicates оставляют первую
встретившуюся строку с данной комбинацией значений. Но если задать параметр
keep='last', то будет оставлена последняя строка:

In [ ]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

### Замена значений

Восполнение отсутствующих данных методом fillna можно рассматривать
как частный случай более общей замены значений. Если метод map, как мы только
что видели, позволяет модифицировать подмножество значений, хранящихся в
объекте, то метод replace предлагает для этого более простой и гибкий интерфейс. Рассмотрим такой объект Series:

In [ ]:
data = Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

Значение -999 могло бы быть маркером отсутствующих данных. Чтобы заменить все такие значения теми, которые понимает pandas, воспользуемся методом
replace, порождающим новый объект Series:

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

Чтобы заменить сразу несколько значений, нужно передать их список и заменяющее значение:

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

Если для каждого заменяемого значения нужно свое заменяющее, то можно передать как
список замен, так и словарь:

In [ ]:
print(data.replace([-999, -1000], [np.nan, 0]), '\n')
print(data.replace({-999: np.nan, -1000: 0}))

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Переименование индексов осей
Как и значения в объекте Series, метки осей можно преобразовывать с помощью функции или отображения, порождающего новые объекты с другими метками. Оси можно также модифицировать на месте, не создавая новую структуру
данных. Вот простой пример:

In [ ]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                 index=['Ohio', 'Colorado', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

Как и у объекта Series, у индексов осей имеется метод map:

In [ ]:
data.index.map(str.upper)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

Индексу можно присваивать значение, т. е. модифицировать DataFrame на месте:

In [ ]:
data.index = data.index.map(str.upper)
data

          one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

Если требуется создать преобразованный вариант набора данных, не меняя
оригинал, то будет полезен метод rename:

In [ ]:
data.rename(index=str.title, columns=str.upper)

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

Интересно, что rename можно использовать в сочетании с похожим на словарь
объектом, который возвращает новые значения для подмножества меток оси:

In [ ]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

          one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

Метод rename избавляет от необходимости копировать объект DataFrame вручную и присваивать значения его атрибутам index и columns. Чтобы модифицировать набор данных на месте, задайте параметр inplace=True:

In [ ]:
# Всегда возвращает ссылку на DataFrame
_ = data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

          one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

### Обнаружение и фильтрация выбросов
Фильтрация или преобразование выбросов – это, в основном, вопрос применения операций с массивами. Рассмотрим объект DataFrame с нормально распределенными данными:

In [ ]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

Допустим, что мы хотим найти в одном из столбцов значения, превышающие 3
по абсолютной величине:

In [ ]:
col = data[3]
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

Чтобы выбрать все строки, в которых встречаются значения, по абсолютной
величине превышающие 3, мы можем воспользоваться методом any для булева
объекта DataFrame:

In [ ]:
data[(np.abs(data) > 3).any(1)]

            0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

Можно также присваивать значения данным, удовлетворяющим этому критерию: Следующий код срезает значения, выходящие за границы интервала от –3 до 3:

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

U-функция np.sign возвращает массив, содержащий 1 и –1 в зависимости от
знака исходного значения.

### Вычисление индикаторных переменных
Еще одно преобразование, часто встречающееся в статистическом моделировании и машинном обучении, – преобразование категориальной переменной в
«фиктивную», или «индикаторную» матрицу. Если в столбце объекта DataFrame
встречается k различных значений, то можно построить матрицу или объект
DataFrame с k столбцами, содержащими только нули и единицы. В библиотеке
pandas для этого имеется функция get_dummies, хотя нетрудно написать и свою
собственную. Вернемся к приведенному выше примеру DataFrame:

In [ ]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})

pd.get_dummies(df['key'])

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

Иногда желательно добавить префикс к столбцам индикаторного объекта
DataFrame, который затем можно будет слить с другими данными. У функции
get_dummies для этой цели предусмотрен аргумент prefix:

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

Если некоторая строка DataFrame принадлежит нескольким категориям, то ситуация немного усложняется. Обратимся к набору данных MovieLens 1M.

In [ ]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('d1_files/movies.dat', sep='::', header=None,
                       engine='python', names=mnames)
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

Чтобы добавить индикаторные переменные для каждого жанра, данные придется немного переформатировать. Сначала, построим список уникальных жанров, встречающихся в наборе данных (с помощью элегантного использования
set.union):

In [ ]:
genre_iter = (set(x.split('|')) for x in movies.genres)
genres = sorted(set.union(*genre_iter))

Теперь для построения индикаторного DataFrame можно, например, начать с
объекта DataFrame, содержащего только нули:

In [ ]:
dummies = DataFrame(np.zeros((len(movies), len(genres))), columns=genres)

Затем перебираем все фильмы и присваиваем элементам в каждой строке объекта dummies значение 1:

In [ ]:
for i, gen in enumerate(movies.genres):
    dummies.loc[i, gen.split('|')] = 1

После этого можно соединить их с movies:

In [ ]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

> Для очень больших наборов данных такой способ построения индикаторных переменных для нескольких категорий быстрым не назовешь. Но, безусловно, можно написать низкоуровневую функцию, в которой будут использованы знания о внутренней структуре объекта DataFrame.

В статистических приложениях бывает полезно сочетать функцию get_
dummies с той или иной функцией дискретизации, например cut:

In [ ]:
values = np.random.rand(10)
values

array([0.31660571, 0.71164193, 0.04603641, 0.53457027, 0.81868953,
       0.39509542, 0.34641123, 0.05340884, 0.93324835, 0.10275095])

In [ ]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           1           0
2           1           0           0           0           0
3           0           0           1           0           0
4           0           0           0           0           1
5           0           1           0           0           0
6           0           1           0           0           0
7           1           0           0           0           0
8           0           0           0           0           1
9           1           0           0           0           0